################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../system/HAL/Src/stm32f7xx_hal.c \
../system/HAL/Src/stm32f7xx_hal_adc.c \
../system/HAL/Src/stm32f7xx_hal_adc_ex.c \
../system/HAL/Src/stm32f7xx_hal_can.c \
../system/HAL/Src/stm32f7xx_hal_cec.c \
../system/HAL/Src/stm32f7xx_hal_cortex.c \
../system/HAL/Src/stm32f7xx_hal_crc.c \
../system/HAL/Src/stm32f7xx_hal_crc_ex.c \
../system/HAL/Src/stm32f7xx_hal_cryp.c \
../system/HAL/Src/stm32f7xx_hal_cryp_ex.c \
../system/HAL/Src/stm32f7xx_hal_dac.c \
../system/HAL/Src/stm32f7xx_hal_dac_ex.c \
../system/HAL/Src/stm32f7xx_hal_dcmi.c \
../system/HAL/Src/stm32f7xx_hal_dcmi_ex.c \
../system/HAL/Src/stm32f7xx_hal_dfsdm.c \
../system/HAL/Src/stm32f7xx_hal_dma.c \
../system/HAL/Src/stm32f7xx_hal_dma2d.c \
../system/HAL/Src/stm32f7xx_hal_dma_ex.c \
../system/HAL/Src/stm32f7xx_hal_dsi.c \
../system/HAL/Src/stm32f7xx_hal_eth.c \
../system/HAL/Src/stm32f7xx_hal_flash.c \
../system/HAL/Src/stm32f7xx_hal_flash_ex.c \
../system/HAL/Src/stm32f7xx_hal_gpio.c \
../system/HAL/Src/stm32f7xx_hal_hash.c \
../system/HAL/Src/stm32f7xx_hal_hash_ex.c \
../system/HAL/Src/stm32f7xx_hal_hcd.c \
../system/HAL/Src/stm32f7xx_hal_i2c.c \
../system/HAL/Src/stm32f7xx_hal_i2c_ex.c \
../system/HAL/Src/stm32f7xx_hal_i2s.c \
../system/HAL/Src/stm32f7xx_hal_irda.c \
../system/HAL/Src/stm32f7xx_hal_iwdg.c \
../system/HAL/Src/stm32f7xx_hal_jpeg.c \
../system/HAL/Src/stm32f7xx_hal_lptim.c \
../system/HAL/Src/stm32f7xx_hal_ltdc.c \
../system/HAL/Src/stm32f7xx_hal_ltdc_ex.c \
../system/HAL/Src/stm32f7xx_hal_mdios.c \
../system/HAL/Src/stm32f7xx_hal_mmc.c \
../system/HAL/Src/stm32f7xx_hal_msp.c \
../system/HAL/Src/stm32f7xx_hal_nand.c \
../system/HAL/Src/stm32f7xx_hal_nor.c \
../system/HAL/Src/stm32f7xx_hal_pcd.c \
../system/HAL/Src/stm32f7xx_hal_pcd_ex.c \
../system/HAL/Src/stm32f7xx_hal_pwr.c \
../system/HAL/Src/stm32f7xx_hal_pwr_ex.c \
../system/HAL/Src/stm32f7xx_hal_qspi.c \
../system/HAL/Src/stm32f7xx_hal_rcc.c \
../system/HAL/Src/stm32f7xx_hal_rcc_ex.c \
../system/HAL/Src/stm32f7xx_hal_rng.c \
../system/HAL/Src/stm32f7xx_hal_rtc.c \
../system/HAL/Src/stm32f7xx_hal_rtc_ex.c \
../system/HAL/Src/stm32f7xx_hal_sai.c \
../system/HAL/Src/stm32f7xx_hal_sai_ex.c \
../system/HAL/Src/stm32f7xx_hal_sd.c \
../system/HAL/Src/stm32f7xx_hal_sdram.c \
../system/HAL/Src/stm32f7xx_hal_smartcard.c \
../system/HAL/Src/stm32f7xx_hal_smartcard_ex.c \
../system/HAL/Src/stm32f7xx_hal_smbus.c \
../system/HAL/Src/stm32f7xx_hal_spdifrx.c \
../system/HAL/Src/stm32f7xx_hal_spi.c \
../system/HAL/Src/stm32f7xx_hal_sram.c \
../system/HAL/Src/stm32f7xx_hal_tim.c \
../system/HAL/Src/stm32f7xx_hal_tim_ex.c \
../system/HAL/Src/stm32f7xx_hal_timebase_rtc_alarm.c \
../system/HAL/Src/stm32f7xx_hal_timebase_rtc_wakeup.c \
../system/HAL/Src/stm32f7xx_hal_timebase_tim.c \
../system/HAL/Src/stm32f7xx_hal_uart.c \
../system/HAL/Src/stm32f7xx_hal_usart.c \
../system/HAL/Src/stm32f7xx_hal_wwdg.c \
../system/HAL/Src/stm32f7xx_ll_adc.c \
../system/HAL/Src/stm32f7xx_ll_crc.c \
../system/HAL/Src/stm32f7xx_ll_dac.c \
../system/HAL/Src/stm32f7xx_ll_dma.c \
../system/HAL/Src/stm32f7xx_ll_dma2d.c \
../system/HAL/Src/stm32f7xx_ll_exti.c \
../system/HAL/Src/stm32f7xx_ll_fmc.c \
../system/HAL/Src/stm32f7xx_ll_gpio.c \
../system/HAL/Src/stm32f7xx_ll_i2c.c \
../system/HAL/Src/stm32f7xx_ll_lptim.c \
../system/HAL/Src/stm32f7xx_ll_pwr.c \
../system/HAL/Src/stm32f7xx_ll_rcc.c \
../system/HAL/Src/stm32f7xx_ll_rng.c \
../system/HAL/Src/stm32f7xx_ll_rtc.c \
../system/HAL/Src/stm32f7xx_ll_sdmmc.c \
../system/HAL/Src/stm32f7xx_ll_spi.c \
../system/HAL/Src/stm32f7xx_ll_tim.c \
../system/HAL/Src/stm32f7xx_ll_usart.c \
../system/HAL/Src/stm32f7xx_ll_usb.c \
../system/HAL/Src/stm32f7xx_ll_utils.c 

OBJS += \
./system/HAL/Src/stm32f7xx_hal.o \
./system/HAL/Src/stm32f7xx_hal_adc.o \
./system/HAL/Src/stm32f7xx_hal_adc_ex.o \
./system/HAL/Src/stm32f7xx_hal_can.o \
./system/HAL/Src/stm32f7xx_hal_cec.o \
./system/HAL/Src/stm32f7xx_hal_cortex.o \
./system/HAL/Src/stm32f7xx_hal_crc.o \
./system/HAL/Src/stm32f7xx_hal_crc_ex.o \
./system/HAL/Src/stm32f7xx_hal_cryp.o \
./system/HAL/Src/stm32f7xx_hal_cryp_ex.o \
./system/HAL/Src/stm32f7xx_hal_dac.o \
./system/HAL/Src/stm32f7xx_hal_dac_ex.o \
./system/HAL/Src/stm32f7xx_hal_dcmi.o \
./system/HAL/Src/stm32f7xx_hal_dcmi_ex.o \
./system/HAL/Src/stm32f7xx_hal_dfsdm.o \
./system/HAL/Src/stm32f7xx_hal_dma.o \
./system/HAL/Src/stm32f7xx_hal_dma2d.o \
./system/HAL/Src/stm32f7xx_hal_dma_ex.o \
./system/HAL/Src/stm32f7xx_hal_dsi.o \
./system/HAL/Src/stm32f7xx_hal_eth.o \
./system/HAL/Src/stm32f7xx_hal_flash.o \
./system/HAL/Src/stm32f7xx_hal_flash_ex.o \
./system/HAL/Src/stm32f7xx_hal_gpio.o \
./system/HAL/Src/stm32f7xx_hal_hash.o \
./system/HAL/Src/stm32f7xx_hal_hash_ex.o \
./system/HAL/Src/stm32f7xx_hal_hcd.o \
./system/HAL/Src/stm32f7xx_hal_i2c.o \
./system/HAL/Src/stm32f7xx_hal_i2c_ex.o \
./system/HAL/Src/stm32f7xx_hal_i2s.o \
./system/HAL/Src/stm32f7xx_hal_irda.o \
./system/HAL/Src/stm32f7xx_hal_iwdg.o \
./system/HAL/Src/stm32f7xx_hal_jpeg.o \
./system/HAL/Src/stm32f7xx_hal_lptim.o \
./system/HAL/Src/stm32f7xx_hal_ltdc.o \
./system/HAL/Src/stm32f7xx_hal_ltdc_ex.o \
./system/HAL/Src/stm32f7xx_hal_mdios.o \
./system/HAL/Src/stm32f7xx_hal_mmc.o \
./system/HAL/Src/stm32f7xx_hal_msp.o \
./system/HAL/Src/stm32f7xx_hal_nand.o \
./system/HAL/Src/stm32f7xx_hal_nor.o \
./system/HAL/Src/stm32f7xx_hal_pcd.o \
./system/HAL/Src/stm32f7xx_hal_pcd_ex.o \
./system/HAL/Src/stm32f7xx_hal_pwr.o \
./system/HAL/Src/stm32f7xx_hal_pwr_ex.o \
./system/HAL/Src/stm32f7xx_hal_qspi.o \
./system/HAL/Src/stm32f7xx_hal_rcc.o \
./system/HAL/Src/stm32f7xx_hal_rcc_ex.o \
./system/HAL/Src/stm32f7xx_hal_rng.o \
./system/HAL/Src/stm32f7xx_hal_rtc.o \
./system/HAL/Src/stm32f7xx_hal_rtc_ex.o \
./system/HAL/Src/stm32f7xx_hal_sai.o \
./system/HAL/Src/stm32f7xx_hal_sai_ex.o \
./system/HAL/Src/stm32f7xx_hal_sd.o \
./system/HAL/Src/stm32f7xx_hal_sdram.o \
./system/HAL/Src/stm32f7xx_hal_smartcard.o \
./system/HAL/Src/stm32f7xx_hal_smartcard_ex.o \
./system/HAL/Src/stm32f7xx_hal_smbus.o \
./system/HAL/Src/stm32f7xx_hal_spdifrx.o \
./system/HAL/Src/stm32f7xx_hal_spi.o \
./system/HAL/Src/stm32f7xx_hal_sram.o \
./system/HAL/Src/stm32f7xx_hal_tim.o \
./system/HAL/Src/stm32f7xx_hal_tim_ex.o \
./system/HAL/Src/stm32f7xx_hal_timebase_rtc_alarm.o \
./system/HAL/Src/stm32f7xx_hal_timebase_rtc_wakeup.o \
./system/HAL/Src/stm32f7xx_hal_timebase_tim.o \
./system/HAL/Src/stm32f7xx_hal_uart.o \
./system/HAL/Src/stm32f7xx_hal_usart.o \
./system/HAL/Src/stm32f7xx_hal_wwdg.o \
./system/HAL/Src/stm32f7xx_ll_adc.o \
./system/HAL/Src/stm32f7xx_ll_crc.o \
./system/HAL/Src/stm32f7xx_ll_dac.o \
./system/HAL/Src/stm32f7xx_ll_dma.o \
./system/HAL/Src/stm32f7xx_ll_dma2d.o \
./system/HAL/Src/stm32f7xx_ll_exti.o \
./system/HAL/Src/stm32f7xx_ll_fmc.o \
./system/HAL/Src/stm32f7xx_ll_gpio.o \
./system/HAL/Src/stm32f7xx_ll_i2c.o \
./system/HAL/Src/stm32f7xx_ll_lptim.o \
./system/HAL/Src/stm32f7xx_ll_pwr.o \
./system/HAL/Src/stm32f7xx_ll_rcc.o \
./system/HAL/Src/stm32f7xx_ll_rng.o \
./system/HAL/Src/stm32f7xx_ll_rtc.o \
./system/HAL/Src/stm32f7xx_ll_sdmmc.o \
./system/HAL/Src/stm32f7xx_ll_spi.o \
./system/HAL/Src/stm32f7xx_ll_tim.o \
./system/HAL/Src/stm32f7xx_ll_usart.o \
./system/HAL/Src/stm32f7xx_ll_usb.o \
./system/HAL/Src/stm32f7xx_ll_utils.o 

C_DEPS += \
./system/HAL/Src/stm32f7xx_hal.d \
./system/HAL/Src/stm32f7xx_hal_adc.d \
./system/HAL/Src/stm32f7xx_hal_adc_ex.d \
./system/HAL/Src/stm32f7xx_hal_can.d \
./system/HAL/Src/stm32f7xx_hal_cec.d \
./system/HAL/Src/stm32f7xx_hal_cortex.d \
./system/HAL/Src/stm32f7xx_hal_crc.d \
./system/HAL/Src/stm32f7xx_hal_crc_ex.d \
./system/HAL/Src/stm32f7xx_hal_cryp.d \
./system/HAL/Src/stm32f7xx_hal_cryp_ex.d \
./system/HAL/Src/stm32f7xx_hal_dac.d \
./system/HAL/Src/stm32f7xx_hal_dac_ex.d \
./system/HAL/Src/stm32f7xx_hal_dcmi.d \
./system/HAL/Src/stm32f7xx_hal_dcmi_ex.d \
./system/HAL/Src/stm32f7xx_hal_dfsdm.d \
./system/HAL/Src/stm32f7xx_hal_dma.d \
./system/HAL/Src/stm32f7xx_hal_dma2d.d \
./system/HAL/Src/stm32f7xx_hal_dma_ex.d \
./system/HAL/Src/stm32f7xx_hal_dsi.d \
./system/HAL/Src/stm32f7xx_hal_eth.d \
./system/HAL/Src/stm32f7xx_hal_flash.d \
./system/HAL/Src/stm32f7xx_hal_flash_ex.d \
./system/HAL/Src/stm32f7xx_hal_gpio.d \
./system/HAL/Src/stm32f7xx_hal_hash.d \
./system/HAL/Src/stm32f7xx_hal_hash_ex.d \
./system/HAL/Src/stm32f7xx_hal_hcd.d \
./system/HAL/Src/stm32f7xx_hal_i2c.d \
./system/HAL/Src/stm32f7xx_hal_i2c_ex.d \
./system/HAL/Src/stm32f7xx_hal_i2s.d \
./system/HAL/Src/stm32f7xx_hal_irda.d \
./system/HAL/Src/stm32f7xx_hal_iwdg.d \
./system/HAL/Src/stm32f7xx_hal_jpeg.d \
./system/HAL/Src/stm32f7xx_hal_lptim.d \
./system/HAL/Src/stm32f7xx_hal_ltdc.d \
./system/HAL/Src/stm32f7xx_hal_ltdc_ex.d \
./system/HAL/Src/stm32f7xx_hal_mdios.d \
./system/HAL/Src/stm32f7xx_hal_mmc.d \
./system/HAL/Src/stm32f7xx_hal_msp.d \
./system/HAL/Src/stm32f7xx_hal_nand.d \
./system/HAL/Src/stm32f7xx_hal_nor.d \
./system/HAL/Src/stm32f7xx_hal_pcd.d \
./system/HAL/Src/stm32f7xx_hal_pcd_ex.d \
./system/HAL/Src/stm32f7xx_hal_pwr.d \
./system/HAL/Src/stm32f7xx_hal_pwr_ex.d \
./system/HAL/Src/stm32f7xx_hal_qspi.d \
./system/HAL/Src/stm32f7xx_hal_rcc.d \
./system/HAL/Src/stm32f7xx_hal_rcc_ex.d \
./system/HAL/Src/stm32f7xx_hal_rng.d \
./system/HAL/Src/stm32f7xx_hal_rtc.d \
./system/HAL/Src/stm32f7xx_hal_rtc_ex.d \
./system/HAL/Src/stm32f7xx_hal_sai.d \
./system/HAL/Src/stm32f7xx_hal_sai_ex.d \
./system/HAL/Src/stm32f7xx_hal_sd.d \
./system/HAL/Src/stm32f7xx_hal_sdram.d \
./system/HAL/Src/stm32f7xx_hal_smartcard.d \
./system/HAL/Src/stm32f7xx_hal_smartcard_ex.d \
./system/HAL/Src/stm32f7xx_hal_smbus.d \
./system/HAL/Src/stm32f7xx_hal_spdifrx.d \
./system/HAL/Src/stm32f7xx_hal_spi.d \
./system/HAL/Src/stm32f7xx_hal_sram.d \
./system/HAL/Src/stm32f7xx_hal_tim.d \
./system/HAL/Src/stm32f7xx_hal_tim_ex.d \
./system/HAL/Src/stm32f7xx_hal_timebase_rtc_alarm.d \
./system/HAL/Src/stm32f7xx_hal_timebase_rtc_wakeup.d \
./system/HAL/Src/stm32f7xx_hal_timebase_tim.d \
./system/HAL/Src/stm32f7xx_hal_uart.d \
./system/HAL/Src/stm32f7xx_hal_usart.d \
./system/HAL/Src/stm32f7xx_hal_wwdg.d \
./system/HAL/Src/stm32f7xx_ll_adc.d \
./system/HAL/Src/stm32f7xx_ll_crc.d \
./system/HAL/Src/stm32f7xx_ll_dac.d \
./system/HAL/Src/stm32f7xx_ll_dma.d \
./system/HAL/Src/stm32f7xx_ll_dma2d.d \
./system/HAL/Src/stm32f7xx_ll_exti.d \
./system/HAL/Src/stm32f7xx_ll_fmc.d \
./system/HAL/Src/stm32f7xx_ll_gpio.d \
./system/HAL/Src/stm32f7xx_ll_i2c.d \
./system/HAL/Src/stm32f7xx_ll_lptim.d \
./system/HAL/Src/stm32f7xx_ll_pwr.d \
./system/HAL/Src/stm32f7xx_ll_rcc.d \
./system/HAL/Src/stm32f7xx_ll_rng.d \
./system/HAL/Src/stm32f7xx_ll_rtc.d \
./system/HAL/Src/stm32f7xx_ll_sdmmc.d \
./system/HAL/Src/stm32f7xx_ll_spi.d \
./system/HAL/Src/stm32f7xx_ll_tim.d \
./system/HAL/Src/stm32f7xx_ll_usart.d \
./system/HAL/Src/stm32f7xx_ll_usb.d \
./system/HAL/Src/stm32f7xx_ll_utils.d 


# Each subdirectory must supply rules for building sources it contributes
system/HAL/Src/%.o: ../system/HAL/Src/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM Cross C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m7 -mthumb -mlittle-endian -mfloat-abi=softfp -mno-unaligned-access -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -ffreestanding -fno-move-loop-invariants -Wall -Wextra  -g3 -DDEBUG -DUSE_FULL_ASSERT -DTRACE -DOS_USE_TRACE_SEMIHOSTING_DEBUG -DSTM32F767xx -DUSE_HAL_DRIVER -DHSE_VALUE=8000000 -I"D:\projects\stm32Template\inc" -I"c:\Program Files (x86)\GNU Tools ARM Embedded\5.4 2016q2\arm-none-eabi\lib" -I"D:\projects\stm32Template\system\CMSIS" -I"D:\projects\stm32Template\system\HAL\Inc" -I"D:\projects\stm32Template\system\inc" -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


